#!/bin/bash

apt-get install bpftool
apt-get install linux-tools-common linux-tools-generic

apt-get install bpfmon 
apt-get install bpftrace 
apt-get install bpfcc-tools 
apt-get install binutils-bpf


