#!/bin/bash

# to be called outside of any container on the host

# debug fwd packet
# debug proto bgp full

# show ipv4 bgp 1 neighbor 10.197.37.2 messages
# show ipv4 bgp 1 neighbor 10.197.37.2 status  
# show ipv4 bgp 1 unicast allroute 10.1.10.11/32
# show ipv4 route CORE 10.1.10.11/32
# show ipv4 route CORE

## ./tools/myexabgp_cmd --announce1 route 10.1.10.11/32 next-hop 10.197.36.2

# ./mynemo-docker-dind --bash-vsmd1 route add 10.2.10.12/32 gw 10.197.36.3
# ./mynemo-docker-dind --bash-vsmd1 route add 10.1.10.11/32 gw 10.197.38.3

# ipv4 route CORE2 10.1.10.11 255.255.255.255 13.1.1.1                                                                                                              
# ipv4 route CORE2 10.2.10.12 255.255.255.255 13.1.1.1

if [ "$1" = "-3" ]; then
  shift 1
  docker exec -ti freertr bash -c '{ echo "'"$1"'"; sleep 0; echo "'"$2"'"; sleep 0; echo "'"$3"'"; echo "exit"; sleep 0; echo "exit"; echo "exit"; } | netcat 127.0.0.1 2323' | tr -d $'\r' | awk '/welcome|line ready|see you later|info userReader.cmdEnter|#exit/ { next; } { print; }'
elif [ "$1" = "-2" ]; then
  shift 1
  docker exec -ti freertr bash -c '{ echo "'"$1"'"; sleep 0; echo "'"$2"'"; echo "exit"; sleep 0; echo "exit"; } | netcat 127.0.0.1 2323' | tr -d $'\r' | awk '/welcome|line ready|see you later|info userReader.cmdEnter|#exit/ { next; } { print; }'
else
  docker exec -ti freertr bash -c '{ echo -e "'"$*"'"; echo "exit"; } | netcat 127.0.0.1 2323' | tr -d $'\r' | awk '/welcome|line ready|see you later|info userReader.cmdEnter|#exit/ { next; } { print; }'
fi

