# Generated by Django 3.2.16 on 2025-02-06 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowspec', '0003_auto_20220310_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoDExtraPermissionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_use_netmask31_in_rules', 'Can use net mask 31 and higher in rules'), ('can_use_netmask30_in_rules', 'Can use net mask 30 and higher in rules'), ('can_use_netmask29_in_rules', 'Can use net mask 29 and higher in rules'), ('can_use_netmask28_in_rules', 'Can use net mask 28 and higher in rules'), ('can_use_netmask27_in_rules', 'Can use net mask 27 and higher in rules'), ('can_use_netmask26_in_rules', 'Can use net mask 26 and higher in rules'), ('can_use_netmask25_in_rules', 'Can use net mask 25 and higher in rules'), ('can_use_netmask24_in_rules', 'Can use net mask 24 and higher in rules'), ('can_use_netmask23_in_rules', 'Can use net mask 23 and higher in rules'), ('can_use_netmask22_in_rules', 'Can use net mask 22 and higher in rules'), ('can_use_netmask21_in_rules', 'Can use net mask 21 and higher in rules'), ('can_use_netmask20_in_rules', 'Can use net mask 20 and higher in rules')),
            },
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Rulex', 'verbose_name_plural': 'Rules'},
        ),
        migrations.AlterField(
            model_name='route',
            name='applier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
