# Generated by Django 4.2 on 2025-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0004_alter_route_applier'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bgpextendedcommunity',
            field=models.CharField(blank=True, choices=[('', 'none'), ('target:20965:333', 'target:20965:333')], default='', max_length=50, null=True),
        ),
    ]
