# Generated by Django 4.2 on 2026-01-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowspec', '0005_route_bgpextendedcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bgprt',
            field=models.CharField(blank=True, choices=[('', 'none'), ('20965:333', '20965:333'), ('20965:331', '20965:331')], default='20965:333', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='bgpextendedcommunity',
            field=models.CharField(blank=True, choices=[('', 'none'), ('target:20965:333', '20965:333'), ('target:20965:331', '20965:331')], default='target:20965:333', max_length=50, null=True),
        ),
    ]
