[main]
debug = false
one_shot = false
raw = false
silent = false
host = localhost
port = 12345

# List of routers
routers = router.1, router.2

# Configuration for router.1
[router.1]
netconf_port = 830
ip_address = X
username = user
password = pass

# Configuration for router.2
[router.2]
netconf_port = 830
ip_address = Y
username = user
password = pass
