[main]
debug = false
one_shot = false
raw = false
silent = false
host = localhost
port = 12345

# List of routers
routers = router.1, router.2

# Configuration for router.1
[router.1]
netconf_port = 830
ip_address = X
username = user
password = pass
telemetry_path_cert = 
telemetry_path_key = 
telemetry_path_root = 
# insecure = false to use transport encryption tls with certificates above
telemetry_insecure = true
# skip_verify = true to skip certificate content verification like CN
telemetry_skip_verify = false


# Configuration for router.2
[router.2]
netconf_port = 830
ip_address = Y
username = user
password = pass
telemetry_path_cert = /path/to/certificate.pem
telemetry_path_key = /path/to/certificate.key
telemetry_path_root = /path/to/caroot.pem
telemetry_insecure = false
telemetry_skip_verify = true
