#!/bin/bash

if [ "$1" = "--run_only" ]; then
  shift 1
  
  exec ./mynemo-mitigation-vsmd-run 2> /nemo-all/vsmd.log

else

  ./mynemo-mitigation-vsmd-install

  exec ./mynemo-mitigation-vsmd-run "$@"

fi

