#!/bin/bash

. /nemo-all/env.sh

export PYTHONPATH="$PYTHONPATH:/nemo-all/nemo-vsmd/lib/python3/:/nemo-all/nemo-offrampctl/lib/python3/"

#cd /nemo-all/nemo-offrampctl/ pip install -r requirements.txt

exec /nemo-all/nemo-offrampctl/bin/offrampctl "$@"


